<h1>New Talk</h1>

<div class="bs-callout bs-callout-warning">
    <h4>Form Failed Validation</h4>

</div>

<?php
    foreach ($form->getMessagesFor('name') as $message) {
        echo $message, '<br>';
    }
?>

<form method="post" role="form" class="form-horizontal">

    <div class="form-group">
        <label class="col-sm-2 control-label">ID</label>
        <div class="col-sm-10">
            <?php echo $form->render("id") ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
            <?php echo $form->render("name") ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Starts</label>
        <div class="col-sm-10">
            <?php echo $form->render("starts") ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Finishes</label>
        <div class="col-sm-10">
            <?php echo $form->render("finishes") ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Status</label>
        <div class="col-sm-10">
            <?php echo $form->render("status") ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>

</form>