<html>
<head>
    <title>Example</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Matthew Setter">
    <?php echo $this->tag->stylesheetLink("css/bootstrap.min.css"); ?>
    <?php echo $this->tag->stylesheetLink("css/starter-template.css"); ?>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Talk It Up</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Talks <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/talks">Upcoming Talks</a></li>
                            <li><a href="/talks/archive">Past Talks</a></li>
                        </ul>
                    </li>
                    <li><a href="/pages/about">About</a></li>
                    <li><a href="/pages/privacy">Privacy</a></li>
                    <li><a href="/pages/copyright">Copyright</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <div class="container">
        <div class="starter-template">
            <?php echo $this->getContent() ?>
        </div>

    </div><!-- /.container -->
    <?php echo $this->tag->javascriptInclude("js/jquery.min.js"); ?>
    <?php echo $this->tag->javascriptInclude("js/bootstrap.min.js"); ?>
</body>
</html>